version: "3.8"
services:
  mongo:
    image: mongo:4.4.4
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - 27017:27017
    volumes:
      - /data/db
    networks:
      - conexa

  cache:
    image: redis:6.2
    ports:
      - 6379:6379
    networks:
      - conexa
  
  auth:
    build: ./auth
    ports:
      - "3001:3001"
    environment:
      NODE_ENV: production
      DB_URI: mongodb://root:example@mongo:27017/mydatabase?authSource=admin
      CACHE_HOST: cache
      HOST_AUTH: auth
      HOST_BUSINESS: business
    depends_on:
      - mongo
      - cache
    networks:
      - conexa

  business:
    build: ./business
    ports:
      - "3002:3002"
    environment:
      NODE_ENV: production
      DB_URI: mongodb://root:example@mongo:27017/mydatabase?authSource=admin
      CACHE_HOST: cache
      HOST_AUTH: auth
      HOST_BUSINESS: business
    depends_on:
      - mongo
      - cache
    networks:
      - conexa

networks:
  conexa:
    driver: bridge